.\" Copyright (C) 1998 David A. Hinds -- dhinds@hyper.stanford.edu
.\" ftl_check.1 1.5 1998/05/04 23:27:48
.\"
.TH FTL_CHECK 1 "1998/05/04 23:27:48" "pcmcia-cs"
.SH NAME
ftl_check \- Flash Translation Layer format checker
.SH SYNOPSIS
.B ftl_check
.I device
.SH DESCRIPTION
.B Ftl_check
dumps a lot of bookkeeping information for a Flash Translation Layer
partition.  It needs to access the flash partition's raw character-mode
device (such as
.IR /dev/mem0c0c ).
It cannot actually fix formatting problems.
.SH AUTHOR
David Hinds \- dhinds@hyper.stanford.edu
.SH "SEE ALSO"
ftl_format(8).
