.\" Copyright (C) 1998 David A. Hinds -- dhinds@hyper.stanford.edu
.\" netwave_cs.4 1.4 1998/05/04 23:28:16
.\"
.TH NETWAVE_CS 4 "1998/05/04 23:28:16" "pcmcia-cs"
.SH NAME
netwave_cs \- Xircom Creditcard Netwave device driver
.SH SYNOPSIS
.B insmod netwave_cs.o
.RB [ pc_debug=n ]
.RB [ domain=n ]
.RB [ scramble_key=n ]
.RB [ mem_speed=n ]
.RB [ irq_list=i,j,... ]
.SH DESCRIPTION
.B Netwave_cs
is the low-level Card Services driver for the Xircom Creditcard
Netwave PCMCIA wireless network adapter.  When this driver is attached
to a card, it allocates the next available ethernet device
.RB ( eth0 .. eth# ).
This
device name will be reported in the kernel log file, and will be
passed on to
.BR cardmgr (8).
.PP
The wireless domain number and scrambling key can be specified using
module parameters when the module is loaded.  These parameters should
be specified in
.IR /etc/pcmcia/config.opts .
.SH PARAMETERS
.TP
.B pc_debug=n
Selects the PCMCIA debugging level.  This parameter is only available
if the module is compiled with debugging enabled.  A non-zero value
enables debugging.
.TP
.B domain=n
Selects what access point(s) to talk to, by their domain number.
Values from 0 to 0x1ff are valid; 0x100 is the default.
.TP
.B scramble_key=n
Selects the scramble key for domains that are scrambled.  Values from
0 to 0x1ff are valid.  The default is 0 (no scrambling).
.TP
.B mem_speed=n
Sets the access speed of the shared memory window, in nanoseconds.
The default is 0 (i.e., no extra wait states).  Values of up to 1000
are legal.
.TP
.B irq_list=i,j,...
Specifies the set of interrupts that may be allocated by this driver.
.SH BUGS
The statistics reported back from the driver are wrong.
.SH AUTHORS
Dag Brattli \- dagb@cs.uit.no
.br
John Markus Bjorndalen \- johnm@staff.cs.uit.no
.br
David Hinds \- dhinds@hyper.stanford.edu
.SH "SEE ALSO"
cardmgr(8), pcmcia(5).
