.\" Copyright (c) 1995 David Hinds <dhinds@allegro.stanford.edu>
.\" pcnet_cs.4 1.7 1997/09/08 02:13:01
.\"
.TH PCNET_CS 4 "1997/09/08 02:13:01" "Stanford University"
.SH NAME
pcnet_cs \- Generic NS8390-based PCMCIA Ethernet Driver
.SH SYNOPSIS
.B insmod pcnet_cs.o
.RB [ pc_debug=n ]
.RB [ irq_list=i,j,... ]
.RB [ if_port=n ]
.RB [ use_shmem=n ]
.RB [ use_big_buf=n ]
.RB [ mem_speed=n ]
.RB [ delay_output=n ]
.RB [ delay_time=n ]
.RB [ hw_addr=n,n,n,n,n,n ]
.SH DESCRIPTION
.B Pcnet_cs
is a driver for all NS8390-based PCMCIA ethernet cards.  It can use
either polled IO or a shared memory window to exchange data with the
card.  It replaces the
.B de650_cs
and
.B ibmcc_cs
drivers in previous releases.  When this driver is bound to a card, it
allocates the next available ethernet device
.RB ( eth0 .. eth# ).
This
device name will be reported in the kernel log file, and passed on to
.BR cardmgr (8).
.SH PARAMETERS
.TP
.B pc_debug=n
Selects the PCMCIA debugging level.  This parameter is only available
if the module is compiled with debugging enabled.  A non-zero value
enables debugging.
.TP
.B irq_list=i,j,...
Specifies the set of interrupts that may be allocated by this driver.
.TP
.B if_port=n
Selects the transceiver type, for Socket EA and IBM CCAE cards.  1 is
10baseT (twisted pair), and 2 is 10base2 (BNC, or thin net).  The
default is 1 (10baseT).
.TP
.B use_shmem=n
Selects whether to use shared memory (if 1) or polled IO (if 0) to
access the card.  If unset, then the default
is to choose based on the card type (shared memory for IBM
CCAE and friends, polled IO for all others).
.TP
.B use_big_buf=n
For Socket EA cards, a flag indicating if the driver should use the
large (64K) packet buffer.  The default is 1 (true).
.TP
.B mem_speed=n
Sets the access speed of the shared memory window, in nanoseconds.
The default is 0 (i.e., no extra wait states).  Values of up to 1000
are legal.
.TP
.B delay_output=n
Specifies that a delay should be inserted after a polled IO block
output.  This is turned on by default for Accton and Socket EA cards.
.TP
.B delay_time=n
Specifies the length of the
.B delay_output
delay, in microseconds.  The default is 4.
.TP
.B hw_addr=n,n,n,n,n,n
For cards whose hardware ethernet addresses can't be identified by the
current driver, this is a hack for hardwiring a specific address.  The
argument should consist of exactly six byte-sized numbers, separated
by commas, with no spaces.  Numbers may be in decimal or hex ('0xNN').
.SH AUTHOR
David Hinds \- dhinds@allegro.stanford.edu
.SH "SEE ALSO"
cardmgr(8), pcmcia(5).
