.\" Copyright (c) 1995 David Hinds <dhinds@allegro.stanford.edu>
.\" serial_cs.4 1.7 1997/09/08 02:13:01
.\"
.TH SERIAL_CS 4 "1997/09/08 02:13:01" "Stanford University"
.SH NAME
serial_cs \- PCMCIA serial port driver
.SH SYNOPSIS
.B insmod serial_cs.o
.RB [ pc_debug=n ]
.RB [ irq_list=i,j,... ]
.RB [ do_sound=n ]
.SH DESCRIPTION
.B Serial_cs
is the Card Services driver for all PCMCIA serial devices, including
modem cards.  When
.B serial_cs
is bound to a serial or modem card, it will generally attempt to
allocate the first unused serial device for use by the card.  The
device chosen will be recorded in the kernel log file, and will also
be reported to
.BR cardmgr (8).
The major and minor numbers and device name reported by
.B serial_cs
will match the corresponding "dialout" device
.RI ( /dev/cua# ).
The new
device can be accessed using this device file or the corresponding
.I /dev/ttyS#
device.  The default serial card setup script will link
the dialout device to
.IR /dev/modem .
.SH PARAMETERS
.TP
.B pc_debug=n
Selects the PCMCIA debugging level.  This parameter is only available
if the module is compiled with debugging enabled.  A non-zero value
enables debugging.
.TP
.B irq_list=i,j,...
Specifies the set of interrupts that may be allocated by this driver.
.TP
.B do_sound=n
A flag specifying if speaker output should be enabled.  The default is
1 (true).  Set to 0 to disable speaker output.
.SH AUTHOR
David Hinds \- dhinds@allegro.stanford.edu
.SH "SEE ALSO"
cardmgr(8), pcmcia(5).
