.\" Copyright (C) 1998 David A. Hinds -- dhinds@hyper.stanford.edu
.\" stab.5 1.9 1999/10/13 23:38:57
.\"
.TH STAB 5 "1999/10/13 23:38:57" "pcmcia-cs"
.SH NAME
stab \- Current PCMCIA socket status
.SH DESCRIPTION
The
.I stab
file is created by
.B cardmgr
and contains identification and device driver information for PCMCIA
cards.  Each socket is described by one header line, followed by one
or more device driver lines.  The header gives the card name as given
in
.IR /etc/pcmcia/config .
Device driver lines consist of a series of tab-separated fields.  The
first field is the socket number.  The second field is the device
class, which identifies which script in
.I /etc/pcmcia
is used to configure or shut down this device.
The third field is the driver name.
The fourth field is used to number devices when a single
card has several devices associated with the same driver.  The fifth
field is the device name, and the final two fields are major and minor
device numbers for this device, if appropriate.
.PP
The file is updated by
.B cardmgr
whenever a card is inserted or ejected, and when
.B cardmgr
receives a
.B SIGHUP
signal.
.PP
The
.I stab
file will normally be created in either
.I /var/state/pcmcia
or
.IR /var/lib/pcmcia ,
but if neither directory is available, it will be found in
.IR /var/run .
.SH AUTHOR
David Hinds \- dhinds@hyper.stanford.edu
.SH "SEE ALSO"
cardmgr(8), pcmcia(5), cardinfo(1).
