.\" Copyright (c) 1997 Werner Koch <werner.koch@guug.de>
.\" xirc2ps_cs.4,v 1.5 1998/09/15 12:40:59 wk Exp
.\"
.TH XIRC2PS_CS 4 "1.5  1998/09/15 12:40:59" ""
.SH NAME
xirc2ps_cs \- Xircom CE2ps (and newer) device driver
.SH SYNOPSIS
.B insmod xirc2ps_cs.o
.RB [ pc_debug=\c
.IR n ]
.RB [ irq_mask=\c
.IR n ]
.RB [ lockup_hack=\c
.IR 1 ]
.SH DESCRIPTION
.B xirc2ps_cs
is the low-level Card Services driver for the Xircom
PCMCIA ethernet adapters.  When this driver is attached to a card, it
allocates the next available ethernet device.
.SH PARAMETERS
.TP
.BI pc_debug= n
Selects the PCMCIA debugging level.  This parameter is only available
if the module is compiled with debugging enabled.  A non-zero value
enables debugging.
.TP
.BI irq_mask= n
Specifies the set of interrupts that may be allocated by this driver.
Each bit of the mask word corresponds to one irq number: 0x0001 is irq
0, 0x0002 is irq 1, etc.
.TP
.BI lockup_hack= 1
Enables a hack to avoid lockups on some cards.	Use this only if you
really have lockup problems with your card.
.SH "SEE ALSO"
cardmgr(8), pcmcia(5).
.SH BUGS
Please report to <xircom-bugs@isil.d.shuttle.de>
.SH AUTHOR
Werner Koch
<werner.koch@guug.de>
